name: Main

on:
  push:
    branches:
      - main


jobs:

  build-test-report:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build, test, and push to Dockerhub registry
        run: |
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
            ./build_test_publish.sh
            docker logout
